POST https://api.mercadopago.com/instore/orders/qr/seller/collectors/1887951604/pos/LOJA1POS1/qrs
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "total_amount": 36.0,
  "external_reference": "8",
  "notification_url": "https://gomesrodris-mplabs.requestcatcher.com/payment-hooks/mercadopago",
  "description": "Pedido 8. Cliente José",
  "title": "Pedido 8",
  "expiration_date": "2024-07-13T18:55:47.855-03:00",
  "items": [
    {
      "sku_number": "2",
      "quantity": 1,
      "total_amount": 23.5,
      "unit_measure": "unit",
      "description": "Hamburger do Futuro com cebolas caramelizadas e cheddar vegano",
      "category": "food",
      "title": "Veggie Cheddar",
      "unit_price": 23.5
    },
    {
      "sku_number": "6",
      "quantity": 1,
      "total_amount": 12.5,
      "unit_measure": "unit",
      "description": "Milk Shake de chocolate, morango ou baunilha. Escolha o sabor na observação",
      "category": "food",
      "title": "Milk shake",
      "unit_price": 12.5
    }
  ]
}
