FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /build
COPY . /build/

RUN ls ./mvnw || (echo Precondition check: docker build deve ser executado na raiz do projeto && false)

RUN ./mvnw -DskipTests install dependency:copy-dependencies

##########################################
FROM eclipse-temurin:21-jdk-alpine AS final

RUN adduser apprunner -D

RUN mkdir /app

COPY --from=builder /build/code/web-app/target/architect-burgers-webapi-*.jar /app/
COPY --from=builder /build/code/web-app/target/lib/* /app/
COPY ./docker/entrypoint.sh /app/

RUN chown -R apprunner /app
RUN chmod a+x /app/entrypoint.sh

USER apprunner

ENV archburgers.datasource.driverClass=org.postgresql.Driver
ENV archburgers.datasource.dbUrl=jdbc:postgresql://pgserver/archburgers?autoReconnect=true
ENV archburgers.datasource.dbUser=myDbUser
ENV archburgers.datasource.dbPass=muDbPass

EXPOSE 8090

CMD /app/entrypoint.sh
