# ### ### ### ### Etapa "0" - Identificação do cliente (opcional)
# # # O serviço /cliente?cpf retorna as informações salvas do cliente.
# # # Frontend deverá apresentar para o cliente para confirmação e guardar ID do cliente para o próximo passo
###
# @name Identifica Cliente
# Identificar cliente pelo CPF
GET {{baseUrl}}/cliente?cpf=12332112340

# ### ### ### ### A primeira etapa é iniciar um novo carrinho de compras
# # # Há 3 opções para iniciar o carrinho:

###
# @name Carrinho opção 1: Novo carrinho cliente identificado
# Cria um novo carrinho utilizando identificação pelo ID do cliente
POST {{baseUrl}}/carrinho
Content-Type: application/json

{
  "idCliente": 1
}

###
# @name Carrinho existente cliente identificado
# Nota: Se o cliente identificado solicitar a criação de um carrinho, e já existe um carrinho aberto
#       para o mesmo, o sistema oferece o recurso de recuperar este carrinho existente. Permite continuar em caso de falha.
POST {{baseUrl}}/carrinho
Content-Type: application/json

{
  "idCliente": 2
}

###
# @name Carrinho opção 2 - Cliente não identificado
# Cliente não identificado é a denominação para clientes não cadastrados na base. A criação de um carrinho de compras
# para cliente não identificado requer apenas um nome para uso como identificação temporária
POST {{baseUrl}}/carrinho
Content-Type: application/json

{
  "nomeCliente": "Cliente José"
}

###
# @name Carrinho opção 3 - Novo carrinho e cadastrar cliente
# Recebe os dados completos do cliente, o pedido será feito como um Cliente Identificado e a partir da próxima compra
# poderá usar a identificação por CPF
POST {{baseUrl}}/carrinho
Content-Type: application/json

{
  "nomeCliente": "Cliente Maria",
  "cpf": "11122233396",
  "email": "maria.cliente@example.org"
}


###
# ### ### ### ### Etapa 2: seleção de itens e montagem do carrinho de compras

###
# @name Consultar carrinho atual
# # # (URL param é o ID do carrinho)
GET {{baseUrl}}/carrinho/1

###
# @name Consulta itens do cardápio
GET {{baseUrl}}/cardapio

###
# @name Add Item ao Carrinho
# # # Recebe no Post o ID do item (consulta cardápio)
POST {{baseUrl}}/carrinho/3
Content-Type: application/json

{
    "idItemCardapio": 6
}

###
# @name Excluir itens do Carrinho
# # # O segundo parâmetro é o número de sequência do item no carrinho
DELETE {{baseUrl}}/carrinho/1/itens/1
Content-Type: application/json


###
# @name Set observacoes no carrinho
PUT {{baseUrl}}/carrinho/1/obs
Content-Type: application/json

{
  "observacoes": "Muito sal na batatinha por favor"
}

###
# ### ### ### ### Etapa 3 - checkout

###
# @name Listar formas pagamento
GET {{baseUrl}}/pagamento/opcoes

###
# @name Criar pedido
# # # Esta ação irá gerar um ID de pedido, que não é igual ao ID do carrinho.
# # # Carrinho será excluído automaticamente
POST {{baseUrl}}/pedidos
Content-Type: application/json

{
  "idCarrinho": 1,
  "formaPagamento": "MercadoPago"
}

###
# # # Pagamento:

###
# @name Consulta status pagamento
GET {{baseUrl}}/pagamento/consulta/6

###
# # # Se o pagamento é local, sem integracao (DINHEIRO, CARTÃO MÁQUINA)
# # # Confirmação abaixo feita pelo Atendente
# @name Confirmação de pagamento
#
POST {{baseUrl}}/pagamento/confirmacao
Content-Type: application/json

{
  "idPedido": 5
}

###
# # # Se o pagamento tem integração externa..
# Cliente consulta QRCode
# @name Consulta QRCode pagamento
{{baseUrl}}/pagamento/consulta/6/qrcode

###
# # # Gateway de pagamento aciona o webhook
# # # (hooks individuais para cada serviço de pagamento)
# @name MercadoPago webhook
{{baseUrl}}/pagamento-webhook/mercado-pago


### ######### Etapa 4 Acompanhamento e preparação
###
# @name Listar pedidos recebidos
GET {{baseUrl}}/pedidos?status=RECEBIDO

###
# @name Validar pedido
POST {{baseUrl}}/pedidos/5/validar

###
# @name Cancelar pedido
POST {{baseUrl}}/pedidos/4/cancelar

###
# @name Listar pedidos em preparação (cozinha)
GET {{baseUrl}}/pedidos?status=PREPARACAO

###
# @name Listar pedidos com atraso
GET {{baseUrl}}/pedidos?atraso=true

###
# @name Atualizar pedido Pronto
POST {{baseUrl}}/pedidos/5/setPronto

###
# @name Finalizar pedido
POST {{baseUrl}}/pedidos/5/finalizar



### ######### Serviços administrativos

# @name Listar todos os pedidos ativos
GET {{baseUrl}}/pedidos

###
# @name Listar todos clientes
GET {{baseUrl}}/clientes

###
# @name Listar itens de cardápio por tipo
GET {{baseUrl}}/cardapio?tipo=ACOMPANHAMENTO

###
# @name Cadastrar um item no cardápio
POST {{baseUrl}}/cardapio
Content-Type: application/json

{
  "tipo": "ACOMPANHAMENTO",
  "nome": "Onion Rings",
  "descricao": "Porção de anéis de cebola empanados",
  "valor": {
    "raw": "15.00"
  }
}

###
# @name Atualizar um item do cardápio
PUT {{baseUrl}}/cardapio/9
Content-Type: application/json

{
  "tipo": "ACOMPANHAMENTO",
  "nome": "Onion Rings M",
  "descricao": "Porção de anéis de cebola empanados tamanho médio",
  "valor": {
    "raw": "16.00"
  }
}

###
# @name Excluir um item do cardápio
DELETE {{baseUrl}}/cardapio/9

